### ISSUE TITLE
Error em Group ele tem que retornar o grupo

### ISSUE THREAD

**Issue by jeffotoni** [gojeffotoni/quick#28]
![image](https://user-images.githubusercontent.com/1092879/221806573-731a5a20-e1c3-4678-98a8-a66f1995066b.png)

![image](https://user-images.githubusercontent.com/1092879/221806599-a242e623-a15d-46a3-8e94-5a9091e9c096.png)

![image](https://user-images.githubusercontent.com/1092879/221806634-7cb6ca04-d306-41cd-ae72-20a84a6d5499.png)

**Comment by marcos-dev88** [comment]
Posso ficar com essa issue @jeffotoni ?

**Comment by jeffotoni** [comment]
Yes sapeca
