### ISSUE TITLE
Tests usando Goroutines error

### ISSUE THREAD

**Issue by jeffotoni** [gojeffotoni/quick#29]
![image](https://user-images.githubusercontent.com/1092879/221807161-ccea8bfc-15d6-469b-b131-62759965b008.png)

Temos que rever para manter syncrono

**Comment by marcos-dev88** [comment]
Com o Listen não tem como pois ele trava a execução do código para executar o server, por isso foi feito o ajuste usando o new Recorder e utilizando o ServeHTTP, essa function está para tesrar o listen. @jeffotoni

**Comment by jeffotoni** [comment]
Blz, depois vamos melhorar ...
